###########################################
#             Configuration               #
#           Plugin by SparnetXD           #
###########################################

# by SparnetXD [TwitchPlugin]
messages:
  twitchNotification: "[Twitch] &6A streamer is live on Twitch! Go live now --> twitch.tv/{twitchUsername}"
