name: TwitchPlugin
version: 1.0-SNAPSHOT
main: queryys.twitchplugin.TwitchPlugin
commands:
  twitch:
    description: Sends a notification when a Twitch streamer goes live
    usage: /twitch <TwitchUsername>
